linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude:
    - Using the variable on range scope `tt` in function literal
    - not declared by package utf8
    - unicode/utf8/utf8.go

run:
  skip-dirs:
    - templates
    - storage

linters:
  enable:
    - goconst
    - gofmt
    - lll
    - misspell
    - scopelint
    - gochecknoinits
    - golint
    - gocyclo
    - gocritic
    - stylecheck
    - goimports
    - gosec
    - unconvert
    - unparam
  disable:
    - gochecknoglobals
    - maligned
    - dupl
    - nakedret
