version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

  test:
    container_name: test_go
    build: .
    restart: on-failure
    env_file:
      - dev.env
    environment:
      DB_HOST: db
      DB_PASSWORD: test
    ports:
      - 5555:5555
    depends_on:
      - db